#!/usr/bin/env bash

declare kx_url kx_bin
declare -i status
kx_url="https://raw.githubusercontent.com/halostatue/kx/main/kx"
kx_bin="$(mktemp)"

command curl -sSL -o "${kx_bin}" "${kx_url}" || {
  status=$?
  echo >&2 "Error downloading ${kx_url}: ${status}"
  exit "${status}"
}

chmod +x "${kx_bin}"
exec "${kx_bin}" --install
